ALPACA_API_KEY = "AKRSPYRQKUINR3XBZ3ER"
ALPACA_SECRET_KEY = "j7XT3cVvrvbcq1VSXZVFodiI87sxYNr0lcNvWWCs"
API_BASE = "https://api.alpaca.markets"
TIMEZONE = "America/New_York"
SYMBOL = "AAPL"
INTERVAL = "1M"

ALPACA_HEADERS = {
    "APCA-API-KEY-ID": ALPACA_API_KEY,
    "APCA-API-SECRET-KEY": ALPACA_SECRET_KEY
}
