ALPACA_API_KEY = "YOUR_ALPACA_API_KEY"
ALPACA_SECRET_KEY = "YOUR_ALPACA_SECRET_KEY"
API_BASE = "https://paper-api.alpaca.markets"
TIMEZONE = "America/New_York"
SYMBOL = "AAPL"
INTERVAL = "1D"

ALPACA_HEADERS = {
    "APCA-API-KEY-ID": ALPACA_API_KEY,
    "APCA-API-SECRET-KEY": ALPACA_SECRET_KEY
}
